### ISSUE TITLE
Allow ReplyTo Address in Notification email

### ISSUE THREAD

**Issue by alecrt** [kjac/FormEditor#23]
Hi kjac,

it would be great if we can set an option to enable replyTo for the Notification email.
I could make a PR if you want, but we should decide the UI logic first.

Thanks,
Alessandro

**Comment by kjac** [comment]
Hi @alecrt,

You need an explicit reply-to option, in addition to the already existing sender email option?

**Comment by alecrt** [comment]
Well, dunno if it's necessary @kjac 

I think that the replyTo field is often (if not always) associated with the sender email field, so a simple checkbox under that field could be enough..

What do you think?

**Comment by kjac** [comment]
@alecrt I was under the impression that the sender would always be used as reply-to if no reply-to was defined...? But just to be on the safe side, how about I just explicitly set the reply-to address to be the same as the sender email?

**Comment by alecrt** [comment]
It's fine for me @kjac !
Thanks

**Comment by kjac** [comment]
@alecrt I'll add it to the upcoming release :)

**Comment by alecrt** [comment]
Great!!! Thanks!!!

**Comment by kjac** [comment]
Fixed. I'm aiming for a new release next week.

**Comment by alecrt** [comment]
Hi @kjac
I re-open this because i think is still missing an important feature: reply-to in notification emails

Suppose an hotel site has a booking form. A customer compile and submit it. The hotel staff receives the notification email and should be able to reply-to the email field in the form.

Admin UI speaking I'd add a new "Reply To" dropdown field where the admin could choose the reply to field.

Does it make sense to you?

Thanks, A.

**Comment by kjac** [comment]
Hi @alecrt,

I get where you're going. But I don't agree with the feature, because the notification email is not one you'd necessarily want to include in a reply to the customer (in your case). The notification email can contain all sorts of internal stuff, depending on how you choose to render it, and setting the customer email as reply-to introduces a risk of accidentally sending internal data to the customer.

I think you should take a different approach to tackling this requirement. Maybe put a "Click here to send the customer an email" button in the notification email. The button would essentially be a mailto-link that'd spawn a new email to the email confirmation recipient, optionally with a predefined subject and body text.

When you're rendering the notification email, you have access to the entire form model, so you should be able to get the confirmation recipient email address with something like this:

```cs
var confirmationRecipientField = Model.AllValueFields().FirstOrDefault(f => f.FormSafeName == Model.EmailConfirmationRecipientsField);
var confirmationRecipientEmail = confirmationRecipientField != null ? confirmationRecipientField.SubmittedValue : null;
```

**Comment by alecrt** [comment]
I understand. 
It makes perfect sense to me.

Thanks, A.

**Comment by alecrt** [comment]
Hi @kjac,

i'd like to discuss about this one more time because our customers are not completly satisfied with the "mailTo button" solution.

As you may have already understood our application is a modded Umbraco CMS which targets hospitality (hotel & B&B web sites). We use your form editor for booking requests when the hotel doesn't have any kind of channels manager or booking software/API.
 
They need the form data submitted in the body of the reply email in order to begin a 1 on 1 discussion with their leads. I'm talking about booking dates, number of rooms, childrens etc..

The mailTo body option is too limited, both in length and content (plain-text only).

I was thinking that one possible solution could be exposing an additional event just before SmtpClient send method fires, with the MailMessage and emailType as args. Then, I could intercept the event and manipulate all MailMessage properties to accomodate my needs.

If you want i can make a pull request for this, but i would like your opinion before.

Thank you very much, as always..b
bye A.

**Comment by kjac** [comment]
Hey @alecrt,

An event sounds like an excellent compromise here. I'll get working on it as soon as possible... shouldn't take long :)

I'll get back to you.

**Comment by alecrt** [comment]
Super Kenn!
Thank you!

p.s. please take also a look at Chain of Responsibility Pattern. It would be a major refactor but coud bring a massive improve in extensibility. 
Merchello has a very good implementation:
https://merchello.readme.io/docs/overview-2 -> Task Chains

**Comment by kjac** [comment]
@alecrt check #101 - would that work for you?

Oh and thanks for the link.

**Comment by alecrt** [comment]
Today I'm out of office but the code seems exactly what I as looking for. 
Tomorrow I'll have a run!
Thanks

**Comment by kjac** [comment]
@alecrt cool, let me know. If it works for you I'll create a new release.

**Comment by alecrt** [comment]
Hi @kjac,

forked and checked: I've added IEnumerable<FieldWithValue> to FormEditorMailCancelEventArgs and renamed it to FormEditorMailEventArgs.

Is it a problem for you?

**Comment by kjac** [comment]
Hey @alecrt,

The `sender` argument in the delegate is the ´FormModel`, and it has an `AllValueFields()` method you can use for that very purpose in your event handler.

The name change is OK, I guess, since the chances of an `AfterSendMail` event ever happening are slim to none.

**Comment by alecrt** [comment]
Ooops, sorry Kenn, my fault. 

So, the event is super fine, you can create a release when you want!

Cheers

**Comment by kjac** [comment]
@alecrt the new release is out now :) 

I opted to keep the delegate name as-is, to keep it in line with the other cancel delegate.
